### ISSUE TITLE
Mac os is case sensitive thous unable to have two files with same name different case

### ISSUE THREAD

**Issue by ravitby** [iiasa/message-ix-models#168]
Running the command "git status" on main branch will reproduce the following output:

```On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   message_ix_models/data/test/snapshot-1/MESSAGEix-GLOBIOM_1.1_R11_no-policy_baseline/demand.csv.gz

no changes added to commit (use "git add" and/or "git commit -a")
```

This issue is preventing pulling the code from git.

**Comment by glatterf42** [comment]
Thanks for reporting this! The issue was anticipated in https://github.com/iiasa/message-ix-models/pull/159#issuecomment-2027018868, but we didn't come up with a solution back then. @khaeru, do you expect that rewriting [this function](https://github.com/iiasa/message-ix-models/blob/8f39459fa2e978f80295d17feb0b052909dbeac2/message_ix_models/report/legacy/pp_utils.py#L1969-L1970) will be enough? If I `grep` for `DEMAND` locally, this is the only place in the code where it appears.

**Comment by glatterf42** [comment]
Or maybe it's feasible to remove the `DEMAND` file from the list of extracted files. Wouldn't this only mean that the snapshot tests would have to extract that one parameter from the excel file instead of it already being extracted? Maybe that's okay for one special case.

**Comment by khaeru** [comment]
> Or maybe it's feasible to remove the `DEMAND` file from the list of extracted files. Wouldn't this only mean that the snapshot tests would have to extract that one parameter from the excel file instead of it already being extracted? Maybe that's okay for one special case.

I think this is the way to go. Isn't that what we previously did with snapshot-0?

**Comment by glatterf42** [comment]
We did, but back then we didn't have any code that actually wanted to access `DEMAND`, as far as I can tell. Still, worth a try here as well :)

**Comment by khaeru** [comment]
Files like DEMAND.csv.gz are used for connecting "simulated solution" data to a message_ix.Reporter. ixmp currently doesn't allow loading variable data into a Scenario directly. These data are used for testing the genno-based reporting.

In contrast, the legacy reporting only knows how to use `Scenario.var()` to retrieve data directly from a Scenario instance, so it can only be tested against an actual solved Scenario, not the "simulated" data. So I believe removing this file will not affect the test in question.
