### ISSUE TITLE
message_data is not installed or cannot be imported

### ISSUE THREAD

**Issue by zsalimian** [iiasa/message-ix-models#34]
Dear Sir,

I installed message_ix_models.model, and in python I used the following commands:

from message_ix_models.model.structure import get_codes
codes = get_codes("node/R14")
codes

It shows me the "message_data is not installed or cannot be imported" error.

Would you please guide me how to solve this?

Regards

**Comment by LauWien** [comment]
Dear @zsalimian,
thank you for reaching out and raising this!
To understand the error message in detail, please share the full traceback and use [GitHub's Markdown formatting](https://guides.github.com/features/mastering-markdown/), in particular code fencing with triple backticks (\`\`\`, described [here](https://guides.github.com/features/mastering-markdown/#examples)). 
Many thanks in advance!
