### ISSUE TITLE
message_data ModuleNotFoundError when using mix-models

### ISSUE THREAD

**Issue by jkikstra** [iiasa/message-ix-models#37]
Follow-up from #36:

when freshly installing `message-ix-models` from source in a new conda environment (python=3.7, on windows), one currently gets the following when running `mix-models --help` (after installing pyam in addition, see #36):

See highlighted an error message for `message_data`, which I assume should not be necessary with `message-ix-models` (public) not supposed to be relying on `message_data` (private).
```
(mdl) C:\Users\kikstra\Documents\GitHub\message-ix-models>mix-models --help
**message_data is not installed or cannot be imported

  File "c:\users\kikstra\documents\github\message-ix-models\message_ix_models\cli.py", line 113, in <module>
    import message_data.cli

ModuleNotFoundError: No module named 'message_data'**

Usage: mix-models [OPTIONS] COMMAND [ARGS]...

  Command-line interface for MESSAGEix-GLOBIOM model tools.

  Every tool and script in this repository is accessible through this CLI.
  Scripts are grouped into commands and sub-commands. For help on specific
  (sub)commands, use --help, e.g.:

          mix-models cd-links --help
          mix-models cd-links run --help

  The top-level options --platform, --model, and --scenario are used by
  commands that access specific message_ix scenarios; these can also be
  specified with --url.

  For more information, see
  https://docs.messageix.org/projects/models2/en/latest/cli.html

Options:
  --url ixmp://PLATFORM/MODEL/SCENARIO[#VERSION]
                                  Scenario URL.
  --platform PLATFORM             Configured platform name.
  --model MODEL                   Model name for some commands.
  --scenario SCENARIO             Scenario name for some commands.
  --version INTEGER               Scenario version.
  --local-data PATH               Base path for local data.
  -v, --verbose                   Print DEBUG-level log messages.
  --help                          Show this message and exit.

Commands:
  export-test-data  Prepare data for testing.
  res               MESSAGEix-GLOBIOM reference energy system (RES).
  techs             Export metadata to technology.csv.
```

**Comment by LauWien** [comment]
Possible related issue: #34.

**Comment by LauWien** [comment]
Added missing "```" in the beginning of the code-block to increase the readability.

**Comment by khaeru** [comment]
This error message is displayed by design: https://github.com/iiasa/message-ix-models/blob/560b5ae6d7ecde42be8d90cbcbd4bbd14ca1cb1d/message_ix_models/cli.py#L112-L125

There's two possibilities here:
1. ModuleNotFoundError: No module named 'message_data'
2. There is some error within `message_data.cli` itself.

In the case of (2), we _do_ want to display the full message. But for (1), we could indeed enhance here to:
- Print a less-verbose warning without the traceback, something like "Warning: message_data is not installed; its commands will be unavailable".
- Add a config setting to allow the user to silence this message permanently on their system.

**Comment by khaeru** [comment]
> It seems that the model doesn't work without message_data.

Per my reply at the duplicate (https://github.com/iiasa/message-ix-models/issues/66#issuecomment-1095074970), it does work, but that particular command `cd-links` is not available without `message_data`.

I wrote that we should also in the docs:
- clarify that the list of available commands is shorter or longer depending on whether or not message_data is installed.
- either explain that the list shown is the longer one, or change it to the shorter one.
