### ISSUE TITLE
Correct R12 node list

### ISSUE THREAD

**Issue by khaeru** [iiasa/message-ix-models#46]
@Jihoon informs that at some point after @guofei2016 added the R12 list in #14, the region code `R12_CPA` was renamed to `R12_RCPA` in some (all?) in-use scenarios in the IIASA ECE databases.

Unless the file in message-ix-models is updated, the code here and in message_data cannot be used to prepare data for these scenarios.

**Comment by Jihoon** [comment]
@guofei2016 confirms that the correct name will be `R12_RCPA`, and `R12_CPA` is outdated. I can see within `message_data `some external data sources (e.g. water and globiom) are correctly updated with `RCPA`, so fixing this yaml will be simple.

**Comment by Jihoon** [comment]
> @guofei2016 confirms that the correct name will be `R12_RCPA`, and `R12_CPA` is outdated. I can see within `message_data `some external data sources (e.g. water and globiom) are already correctly updated with `RCPA`, so fixing this yaml will be simple.

But it will involve the following changes in R12 data for transport, as discussed with @khaeru.

**Comment by khaeru** [comment]
https://github.com/iiasa/message-ix-models/commit/490fa9cbd3a46bc84a4ca91f4eb777b635de300c#commitcomment-67296693
> I should make a PR for this change...

@guofei2016 this is correct. Partly my fault: I had not turned on the feature that ensures no one pushes directly to `main`.

I explained in Slack to @Jihoon, but maybe I should have written to you directly:
> > do we also need a PR (I guess theoretically yes but..) or can it be directly done on master?
>
> Yes. Suppose there was someone else using the code (maybe it was just me), expecting it to output stuff with R12_CPA, and then suddenly it starts producing R12_RCPA. They should be able to find out in the release notes what happened and why, like "The code R12_CPA is changed to R12_RCPA to match current usage in IIASA ECE scenarios."
 
 Please do open a PR to do that.

**Comment by guofei2016** [comment]
@khaeru Thanks a lot and I just make a PR!

**Comment by khaeru** [comment]
Closed via #49.
